[package]
name = "extism-runtime"
version = "0.1.0"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/extism"
description = "Extism runtime component"

[dependencies]
wasmtime = "3.0.0"
wasmtime-wasi = "3.0.0"
wasmtime-wasi-nn = {version = "3.0.0", optional=true}
anyhow = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
toml = "0.5"
sha2 = "0.10"
log = "0.4"
log4rs = "1.1"
url = "2"
glob = "0.3"
extism-manifest = { version = "0.1.0", path = "../manifest" }
pretty-hex = { version = "0.3" }
reqwest = {version = "0.11", features = ["blocking"], optional=true}

[features]
default = ["http", "register-http", "register-filesystem"]
nn = ["wasmtime-wasi-nn"]
register-http = ["reqwest"] # enables wasm to be downloaded using http
register-filesystem = []    # enables wasm to be loaded from disk
http = ["reqwest"]          # enables extism_http_request

[build-dependencies]
cbindgen = "0.24"
