on:
  workflow_dispatch:

name: Release Elixir SDK

jobs:
  release-sdks:
    name: release-elixir
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEX_PM_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust ENV (to compile NIF)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Setup Elixir Env
        uses: erlef/setup-beam@v1
        with:
          experimental-otp: true
          otp-version: '25.0.4'
          elixir-version: '1.14.0'

      - name: Publish Elixir Host SDK to hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_PM_API_TOKEN }}
        run: |
          cd elixir
          cp ../LICENSE .
          make publish
  
